apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sp-api-wrapper.fullname" . }}-config
  labels:
    {{- include "sp-api-wrapper.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}