apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sp-api-wrapper.fullname" . }}-secret
  labels:
    {{- include "sp-api-wrapper.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}