import fs from 'fs/promises';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// --- Configuration ---
const MODELS_DIR = path.join(process.cwd(), 'models');
const GEN_DIR = path.join(process.cwd(), 'src/generated');
const TYPES_DIR = path.join(process.cwd(), 'src/types');
const CONFIG_DIR = path.join(process.cwd(), 'src/config');
const RATE_LIMITS_FILE = path.join(CONFIG_DIR, 'rate-limits.json');
const ROUTERS_FILE = path.join(GEN_DIR, 'routers.ts');
const OPENAPI_FILE = path.join(GEN_DIR, 'openapi.ts');

interface RateLimitInfo {
  requestsPerSecond: number;
  burstLimit: number;
}

const rateLimitRegex = /Rate \(requests per second\) \| Burst\s*\|\s*-+\s*\|\s*-+\s*\|\s*([\d.]+)\s*\|\s*(\d+)/;

/**
 * Extracts rate limit information from the description of an operation.
 */
function extractRateLimit(description: string): RateLimitInfo | null {
  const match = description.match(rateLimitRegex);
  if (match && match[1] && match[2]) {
    return {
      requestsPerSecond: parseFloat(match[1]),
      burstLimit: parseInt(match[2], 10),
    };
  }
  return null;
}

/**
 * Converts a string from snake_case or kebab-case to camelCase.
 * e.g., listings-restrictions -> listingsRestrictions
 */
function toCamelCase(str: string): string {
  return str.replace(/([-_][a-z])/ig, ($1) => {
    return $1.toUpperCase()
      .replace('-', '')
      .replace('_', '');
  });
}

/**
 * Converts a Swagger/OpenAPI path to a Hono-compatible path.
 * e.g., /orders/v0/orders/{orderId} -> /orders/v0/orders/:orderId
 */
function formatHonoPath(swaggerPath: string): string {
  return swaggerPath.replace(/{/g, ':').replace(/}/g, '');
}

/**
 * Generates the content for the dynamic routers file.
 * Groups specs by model name to create a single router for each model.
 */
function createRoutersFileContent(routerSpecs: { modelName: string; spec: any }[]): string {
  let content = `
// This file is auto-generated by src/generate.ts. Do not edit manually.
import { Hono } from 'hono';
import { SpApiService } from '../services/sp-api.service';
import { HTTPException } from 'hono/http-exception';

export const generatedRouters = new Map<string, Hono>();
`;

  const groupedSpecs: Record<string, any[]> = {};
  for (const { modelName, spec } of routerSpecs) {
    if (!groupedSpecs[modelName]) {
      groupedSpecs[modelName] = [];
    }
    groupedSpecs[modelName].push(spec);
  }

  for (const modelName in groupedSpecs) {
    const routerVarName = `${modelName.replace(/-/g, '_')}Router`;
    const camelCaseEndpoint = toCamelCase(modelName);

    content += `
// --- Router for ${modelName} ---
const ${routerVarName} = new Hono();
`;

    const specsForModel = groupedSpecs[modelName] ?? [];
    for (const spec of specsForModel) {
      for (const swaggerPath in spec.paths) {
        const pathItem = spec.paths[swaggerPath];
        for (const method in pathItem) {
          const operation = pathItem[method];
          const honoPath = formatHonoPath(swaggerPath);
          const operationId = operation.operationId;

          if (!operationId) continue;

          content += `
${routerVarName}.${method}('${honoPath}', async (c) => {
  try {
    const params = {
      path: c.req.param(),
      query: c.req.query(),
      body: c.req.header('content-type')?.includes('json') ? await c.req.json() : undefined,
    };
    const result = await SpApiService.callApi('${camelCaseEndpoint}', '${operationId}', params);
    return c.json(result);
  } catch (error: any) {
    console.error('Error in generated route for ${operationId}:', error);
    throw new HTTPException(500, { message: \`Failed to call ${operationId}\`, cause: error });
  }
});
`;
        }
      }
    }
    content += `
generatedRouters.set('${modelName}', ${routerVarName});
`;
  }

  return content;
}


/**
 * Main function to generate all dynamic parts of the application.
 */
async function generate() {
  console.log('🚀 Starting API generation...');

  // Clean and ensure generated directories exist
  await fs.rm(GEN_DIR, { recursive: true, force: true });
  await fs.rm(TYPES_DIR, { recursive: true, force: true });
  await fs.mkdir(GEN_DIR, { recursive: true });
  await fs.mkdir(TYPES_DIR, { recursive: true });
  await fs.mkdir(CONFIG_DIR, { recursive: true });

  const modelDirs = await fs.readdir(MODELS_DIR);
  const allRateLimits: Record<string, RateLimitInfo> = {};
  const allPaths: Record<string, any> = {};
  const allDefinitions: Record<string, any> = {};
  const allParameters: Record<string, any> = {};
  const allTags = new Set<string>();
  const routerSpecs: { modelName: string; spec: any }[] = [];

  for (const dirName of modelDirs) {
    const modelPath = path.join(MODELS_DIR, dirName);
    const stats = await fs.stat(modelPath);

    if (stats.isDirectory()) {
      const files = await fs.readdir(modelPath);
      const swaggerFiles = files.filter(f => f.endsWith('.json'));
      const modelName = dirName.replace(/-api-model$/, '').replace(/-model$/, '');

      if (swaggerFiles.length > 0) {
        console.log(`\nProcessing model: ${modelName}`);

        for (const swaggerFile of swaggerFiles) {
            const filePath = path.join(modelPath, swaggerFile);
            const fileContent = await fs.readFile(filePath, 'utf-8');
            const spec = JSON.parse(fileContent);
            routerSpecs.push({ modelName, spec });

            // 1. Generate Types
            const safeModelName = modelName.replace(/-/g, '_');
            const safeFileName = swaggerFile.replace('.json', '').replace(/-/g, '_');
            const typeFileName = `${safeModelName}_${safeFileName}.types.ts`;

            try {
                await execAsync(
                    `bunx swagger-typescript-api generate -p "${filePath}" -o "${TYPES_DIR}" -n "${typeFileName}" --no-client --add-readonly`
                );
                console.log(`  - ✅ Generated types: ${typeFileName}`);
            } catch (e) {
                console.error(`  - ❌ Failed to generate types for ${modelName} from ${swaggerFile}`);
                continue;
            }

            // 2. Merge paths, definitions, and tags
            if (spec.paths) {
                for (const pathKey in spec.paths) {
                    // Use a version prefix if available, otherwise default to modelName
                    const versionPrefix = spec.basePath ? spec.basePath.split('/')[1] : modelName;
                    const apiPath = `/api/${versionPrefix}${pathKey}`;
                    allPaths[apiPath] = spec.paths[pathKey];

                    const pathItem = spec.paths[pathKey];
                    for (const method in pathItem) {
                        const operation = pathItem[method];
                        if (operation.tags && operation.tags.length > 0) {
                            operation.tags.forEach((tag: string) => allTags.add(tag));
                        }

                        if (operation.operationId && operation.description) {
                            const rateLimit = extractRateLimit(operation.description);
                            if (rateLimit) {
                                allRateLimits[operation.operationId] = rateLimit;
                            }
                        }
                    }
                }
            }
            if (spec.definitions) {
                Object.assign(allDefinitions, spec.definitions);
            }

            // 3. Merge top-level (global) Swagger 2.0 parameters for $ref like #/parameters/Foo
            // Some SP-API models (e.g. Notifications) define reusable parameters at the document root.
            if (spec.parameters) {
              for (const [paramKey, paramValue] of Object.entries(spec.parameters)) {
                if (!(paramKey in allParameters)) {
                  allParameters[paramKey] = paramValue;
                  continue;
                }

                const existing = JSON.stringify(allParameters[paramKey]);
                const incoming = JSON.stringify(paramValue);
                if (existing !== incoming) {
                  console.warn(
                    `  - ⚠️  Conflicting global parameter name '${paramKey}'. Keeping the first definition and ignoring the later one from ${modelName}/${swaggerFile}.`
                  );
                }
              }
            }
        }
      }
    }
  }

  // 3. Write Rate Limits file
  await fs.writeFile(RATE_LIMITS_FILE, JSON.stringify(allRateLimits, null, 2));
  console.log(`\n- ✅ All rate limits written to ${RATE_LIMITS_FILE}`);

  // 4. Write Routers file
  const routersFileContent = createRoutersFileContent(routerSpecs);
  await fs.writeFile(ROUTERS_FILE, routersFileContent);
  console.log(`- ✅ Dynamic routers written to ${ROUTERS_FILE}`);

  // 5. Write Combined Swagger 2.0 Spec file
  const finalSpec = {
    swagger: '2.0',
    info: {
      title: 'Amazon SP-API Wrapper (Dynamically Generated)',
      version: '1.0.0',
      description: 'A dynamically generated REST API that wraps the Amazon Selling Partner API with intelligent rate limiting.'
    },
    tags: Array.from(allTags).map(tag => ({ name: tag })),
    paths: allPaths,
    definitions: allDefinitions,
    parameters: allParameters,
    securityDefinitions: {
      ApiKeyAuth: {
        type: 'apiKey',
        in: 'header',
        name: 'X-API-Key'
      }
    },
    security: [
      {
        ApiKeyAuth: []
      }
    ]
  };
  const openApiFileContent = `// This file is auto-generated by src/generate.ts. Do not edit manually.\nexport const openApiSpec = ${JSON.stringify(finalSpec, null, 2)};`;
  await fs.writeFile(OPENAPI_FILE, openApiFileContent);
  console.log(`- ✅ OpenAPI specification written to ${OPENAPI_FILE}`);

  console.log('\n🎉 Generation complete!');
}

generate().catch(error => {
    console.error("\n❌ An error occurred during generation:", error);
    process.exit(1);
});