name: Release Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create gh-pages branch if it does not exist
        run: |
          git rev-parse --verify origin/gh-pages || git checkout --orphan gh-pages && git reset --hard && git commit --allow-empty -m "Initial gh-pages commit" && git push origin gh-pages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Copy chart files to gh-pages
        run: |
          if [ -d ".cr-release-packages" ] && [ "$(ls -A .cr-release-packages)" ]; then
            cp -r .cr-release-packages/* .
          else
            echo "No chart packages to copy."
          fi

      - name: Commit and push changes to gh-pages
        run: |
          git add .
          git commit -m "Update Helm chart release files" || echo "No changes to commit"
          git push origin gh-pages
