name: Release Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Copy chart files to gh-pages folder
        run: |
          mkdir -p gh-pages
          if [ -d ".cr-release-packages" ] && [ "$(ls -A .cr-release-packages)" ]; then
            cp -r .cr-release-packages/* gh-pages/
          else
            echo "No chart packages to copy."
          fi

      - name: Commit and push changes to dev
        run: |
          git add gh-pages/
          git commit -m "Update Helm chart release files in gh-pages folder" || echo "No changes to commit"
          git push origin dev
